/**
 * Document Generation domain types (Fase 12).
 *
 * Pure types — no I/O, no framework, per ARCHITECTURE.md §4.
 *
 * The document generation system transforms case analysis results into
 * formal documents the user can review, edit, and submit.
 *
 * Core principle:
 *   AI drafts → Deterministic validation → User reviews → Final document
 *
 * NEVER:
 *   - AI inventing facts, sources, or legal articles
 *   - Unconfirmed facts becoming factual assertions
 *   - Unsupported claims becoming legal assertions
 *   - Document marked FINAL without user action
 */
import type { FactKey } from "../types";

// ── Document Type ───────────────────────────────────────────────────

/**
 * Closed vocabulary of document types.
 * Controls title, structure, recipient, purpose, tone, sections.
 * Legal logic stays in the Rule/Result Engine.
 */
export type DocumentType =
  | "CONSUMER_COMPLAINT"
  | "REFUND_REQUEST"
  | "WARRANTY_CLAIM"
  | "FLIGHT_CANCELLATION_CLAIM"
  | "GENERAL_FORMAL_REQUEST";

// ── Document Status ─────────────────────────────────────────────────

/**
 * Explicit lifecycle. A document is NEVER automatically FINAL.
 * FINAL requires user review/acceptance.
 */
export type DocumentStatus =
  "DRAFT" | "VALIDATED" | "USER_EDITED" | "FINAL" | "EXPORTED" | "REVOKED";

// ── Document Format ─────────────────────────────────────────────────

export type DocumentFormat = "txt" | "pdf" | "docx";

// ── Document Section ────────────────────────────────────────────────

/**
 * A section within a generated document.
 * Each section traces its content to facts, claims, and sources.
 */
export interface DocumentSection {
  readonly id: string;
  readonly type:
    | "HEADER"
    | "INTRODUCTION"
    | "FACTS"
    | "EVIDENCE"
    | "LEGAL_BASIS"
    | "REQUEST"
    | "DEADLINE"
    | "ATTACHMENTS"
    | "REFERENCES"
    | "SIGNATURE"
    | "CUSTOM";
  readonly title: string;
  readonly content: string;
  /** Fact keys this section references. */
  readonly factKeys: readonly FactKey[];
  /** Claim IDs this section references. */
  readonly claimIds: readonly string[];
  /** Source IDs this section references. */
  readonly sourceIds: readonly string[];
  /** Whether this section was generated by AI or written by the user. */
  readonly origin: "SYSTEM_GENERATED" | "USER_EDITED";
}

// ── Document Citation ───────────────────────────────────────────────

/**
 * A citation linking a document assertion to a verified source.
 * Internal traceability — may not all be shown as footnotes.
 */
export interface DocumentCitation {
  readonly id: string;
  /** The assertion text this citation supports. */
  readonly assertionRef: string;
  /** Source reference ID. */
  readonly sourceId: string;
  /** Source title. */
  readonly sourceTitle: string;
  /** Specific article/section of the source. */
  readonly articleRef?: string;
  /** Source URL. */
  readonly sourceUrl: string;
}

// ── Factual Statement ───────────────────────────────────────────────

/**
 * A factual statement in the document, traceable to a confirmed fact.
 * Only CONFIRMED facts can become factual statements.
 */
export interface FactualStatement {
  readonly factKey: FactKey;
  readonly factId: string;
  /** The statement text derived from the fact. */
  readonly text: string;
  /** Whether the fact is confirmed or requires qualification. */
  readonly confidence: "CONFIRMED" | "QUALIFIED";
  /** Qualification note (e.g., "según la información aportada"). */
  readonly qualification?: string;
}

// ── Legal Statement ─────────────────────────────────────────────────

/**
 * A legal statement in the document, traceable to a supported claim.
 * Only SUPPORTED claims can become legal assertions.
 */
export interface LegalStatement {
  readonly claimId: string;
  readonly ruleKey: string;
  /** The legal assertion text derived from the claim. */
  readonly text: string;
  /** Citation IDs supporting this statement. */
  readonly citationIds: readonly string[];
}

// ── Unresolved Item ─────────────────────────────────────────────────

/**
 * An item that remains unresolved in the document.
 * Contradictions and missing information that the user should address.
 */
export interface UnresolvedItem {
  readonly type: "CONTRADICTION" | "MISSING_INFORMATION" | "UNCONFIRMED_FACT";
  readonly description: string;
  readonly factKey?: FactKey;
  readonly claimId?: string;
}

// ── Generated Document ──────────────────────────────────────────────

/**
 * A versioned, traceable document generated from case analysis.
 * Historical versions are NEVER overwritten.
 */
export interface GeneratedDocument {
  readonly id: string;
  readonly caseId: string;
  readonly type: DocumentType;
  readonly status: DocumentStatus;
  readonly version: number;
  readonly format: DocumentFormat;

  /** Document metadata */
  readonly title: string;
  readonly recipient: string;
  readonly subject: string;

  /** Content sections */
  readonly sections: readonly DocumentSection[];

  /** Traceable assertions */
  readonly factualStatements: readonly FactualStatement[];
  readonly legalStatements: readonly LegalStatement[];
  readonly citations: readonly DocumentCitation[];
  readonly unresolvedItems: readonly UnresolvedItem[];

  /** Provenance */
  readonly analysisSnapshotId?: string;
  readonly aiRequestId?: string;
  readonly promptId?: string;
  readonly promptVersion?: number;

  /** Storage */
  readonly storageKey?: string;
  readonly fileSize?: number;

  /** Timestamps */
  readonly createdAt: string;
  readonly updatedAt: string;

  /** Previous version ID (for version chain) */
  readonly previousVersionId?: string;
}

// ── Document Generation Input ───────────────────────────────────────

/**
 * Structured input for document generation.
 * Built from case data — NOT the raw Case object.
 * Only contains information the AI needs to draft.
 */
export interface DocumentGenerationInput {
  readonly documentType: DocumentType;
  readonly jurisdiction: string;
  readonly language: string;

  /** Sender information (user-provided). */
  readonly sender: {
    readonly name?: string;
    readonly address?: string;
    readonly email?: string;
    readonly phone?: string;
  };

  /** Recipient information (from problem module or user). */
  readonly recipient: {
    readonly name: string;
    readonly address?: string;
    readonly email?: string;
  };

  /** Only CONFIRMED facts. */
  readonly confirmedFacts: readonly FactualStatement[];

  /** Only SUPPORTED claims. */
  readonly supportedClaims: readonly LegalStatement[];

  /** Verified sources referenced by claims. */
  readonly applicableSources: readonly DocumentCitation[];

  /** Relevant timeline events. */
  readonly timeline: readonly {
    readonly date: string;
    readonly description: string;
  }[];

  /** The specific action/request. */
  readonly requestedAction: string;

  /** Case metadata. */
  readonly caseMetadata: {
    readonly problemKey: string;
    readonly problemTitle: string;
    readonly createdAt: string;
    readonly jurisdiction?: string;
    readonly language?: string;
  };

  /** Analysis snapshot for traceability. */
  readonly analysisSnapshotId?: string;

  /** Contradictions and missing info to flag. */
  readonly unresolvedItems: readonly UnresolvedItem[];
}

// ── Generated Draft (AI Output Schema) ──────────────────────────────

/**
 * The structured output from the AI draft generation.
 * Validated with Zod before use.
 * Each statement must trace to a fact or claim in the input.
 */
export interface GeneratedDraft {
  readonly title: string;
  readonly subject: string;
  readonly sections: readonly {
    readonly type: DocumentSection["type"];
    readonly title: string;
    readonly content: string;
  }[];
  readonly factualStatements: readonly {
    readonly factKey: string;
    readonly text: string;
  }[];
  readonly legalStatements: readonly {
    readonly claimId: string;
    readonly text: string;
  }[];
  readonly requestedActions: readonly string[];
  readonly unresolvedItems: readonly {
    readonly type: string;
    readonly description: string;
  }[];
}
