import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { Logo } from "@/components/Logo";
import { Nav } from "@/components/Nav";
import { PlausibleLoader } from "@/components/PlausibleLoader";
import "./globals.css";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const plausibleDomain = process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN;

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"),
  title: {
    default: "Resolveo",
    template: "%s · Resolveo",
  },
  description:
    "Entiende tu problema de consumo. Analizamos tu caso con normativa verificable y te mostramos qué puedes hacer.",
  robots: process.env.NODE_ENV === "production" ? undefined : { index: false, follow: false },
  icons: {
    icon: "/favicon.svg",
  },
  openGraph: {
    title: "Resolveo",
    description:
      "Entiende tu problema de consumo. Analizamos tu caso con normativa verificable y te mostramos qué puedes hacer.",
    type: "website",
    locale: "es_ES",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#1a1a1a",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Resolveo",
    url: siteUrl,
    description:
      "Entiende tu problema de consumo. Analizamos tu caso con normativa verificable y te mostramos qué puedes hacer.",
  };

  const websiteSchema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Resolveo",
    url: siteUrl,
  };

  return (
    <html lang="es">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font -- App Router: fonts loaded in root layout */}
        <link
          href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {/*
          Google Privacy & Messaging (CMP for AdSense).
          When AdSense is configured, paste the exact snippet generated by:
          AdSense → Privacy & messaging → European regulations → Manage → Copy tag

          Do NOT invent URLs, IDs, or parameters. Use only what Google provides.
        */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
      </head>
      <body className="min-h-screen bg-[var(--surface-page)] text-[var(--color-ink)] antialiased">
        <div className="min-h-screen flex flex-col">

          {/* ── Header ───────────────────────────────────────────── */}
          <header className="sticky top-0 z-50 bg-[var(--surface-page)]/90 backdrop-blur-md border-b border-[var(--border-light)]">
            <div className="max-w-[1200px] mx-auto px-5 md:px-8 h-14 flex items-center justify-between">
              <Logo size="sm" />
              <Nav />
            </div>
          </header>

          {/* ── Main ─────────────────────────────────────────────── */}
          <main className="flex-1">{children}</main>

          {/* ── Footer ───────────────────────────────────────────── */}
          <footer className="border-t border-[var(--border-light)] bg-[var(--surface-paper)]">
            <div className="max-w-[1200px] mx-auto px-5 md:px-8">
              <div className="py-12 grid grid-cols-1 md:grid-cols-12 gap-10">

                {/* Brand */}
                <div className="md:col-span-5">
                  <Logo size="sm" linked={false} />
                  <p className="mt-4 text-sm text-[var(--color-ink-muted)] leading-relaxed max-w-xs">
                    Una forma más clara de entender qué hacer cuando algo sale mal con una compra, un servicio o un vuelo.
                  </p>
                </div>

                {/* Producto */}
                <div className="md:col-span-3">
                  <p className="label">Producto</p>
                  <ul className="space-y-2.5">
                    <li><Link href="/" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Resolver un problema</Link></li>
                    <li><Link href="/problemas" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Problemas</Link></li>
                    <li><Link href="/como-funciona" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Cómo funciona</Link></li>
                    <li><Link href="/fuentes" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Fuentes</Link></li>
                  </ul>
                </div>

                {/* Información */}
                <div className="md:col-span-4">
                  <p className="label">Información</p>
                  <ul className="space-y-2.5">
                    <li><Link href="/sobre" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Sobre Resolveo</Link></li>
                    <li><Link href="/contacto" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Contacto</Link></li>
                    <li><Link href="/autor" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Autor</Link></li>
                    <li><Link href="/privacidad" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Privacidad</Link></li>
                    <li><Link href="/cookies" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Cookies</Link></li>
                    <li><Link href="/terminos" className="text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors">Términos</Link></li>
                  </ul>
                </div>
              </div>

              {/* Bottom */}
              <div className="py-5 border-t border-[var(--border-light)] flex flex-col md:flex-row items-center justify-between gap-3">
                <p className="text-xs text-[var(--color-ink-faint)]">
                  &copy; {new Date().getFullYear()} Resolveo
                </p>
                <p className="text-xs text-[var(--color-ink-faint)]">
                  Información basada en normativa vigente. No constituye asesoría legal.
                </p>
              </div>
            </div>
          </footer>
        </div>
        {plausibleDomain && <PlausibleLoader domain={plausibleDomain} />}
      </body>
    </html>
  );
}
