/**
 * GoogleConsentCmp — the certified CMP tag for AdSense, loaded only when configured.
 *
 * What this is
 * ------------
 * Google Privacy & Messaging (AdSense → Privacidad y mensajería → Reglamentos
 * europeos) generates a tag for the certified CMP. That tag is a single script
 * whose `src` contains the publisher-specific URL. This component renders
 * exactly that URL and nothing else.
 *
 * What this deliberately does NOT do
 * ----------------------------------
 *  - No CMP ID, publisher ID, nonce or query parameter is built here. The whole
 *    `src` comes from `NEXT_PUBLIC_GOOGLE_CMP_SRC`, copied verbatim from the tag
 *    Google generates. Guessing the URL structure is how a site ends up with a
 *    consent banner that looks installed but never loads.
 *  - No TCF implementation. The certified CMP already speaks TCF and Consent
 *    Mode; re-implementing `__tcfapi` or reading `purpose.consents` by hand
 *    would duplicate it incorrectly.
 *  - No analytics gating. Plausible is cookieless and runs independently (see
 *    `PlausibleLoader`): analytics consent is not tied to advertising consent,
 *    so it is not read from here.
 *
 * Until the variable is set this renders nothing — the site simply has no CMP
 * yet, which is the honest state rather than a placeholder that pretends to be
 * one.
 */
import { createElement } from "react";

interface GoogleConsentCmpProps {
  /**
   * Full script URL from the tag generated by AdSense. When absent the component
   * renders nothing, so an unconfigured environment never ships a broken tag.
   */
  readonly src?: string | null;
}

/**
 * Rejects anything that is not an https URL on a google.com host.
 *
 * The value is pasted by hand, so this is a guard against a typo silently
 * loading a third-party script on every page. It is a safety check, not a
 * substitute for copying the tag exactly as Google provides it.
 */
export function isValidCmpSrc(src: string): boolean {
  try {
    const url = new URL(src);
    if (url.protocol !== "https:") return false;
    return url.hostname === "google.com" || url.hostname.endsWith(".google.com");
  } catch {
    return false;
  }
}

export function GoogleConsentCmp({ src }: GoogleConsentCmpProps) {
  const tag = src?.trim();
  if (!tag || !isValidCmpSrc(tag)) return null;

  // `createElement` instead of JSX so the guard stays unit-testable without a
  // DOM environment (the project's tests run in node, with the classic JSX
  // runtime).
  return createElement("script", { async: true, src: tag });
}
